[package]
name = "window"
version = "0.1.0"
edition = "2024"
authors = ["Saad Moazzam"]

[lib]
crate-type = ["cdylib","rlib"]

[dependencies]
winit = "0.30.9"

[profile.dev]
opt-level = 3
panic = "abort"

[profile.release]
opt-level = 3
panic = "abort"
